name: workflow_environment_protection

on:
  push:
    branches:
      - 'main'

jobs:
  pre-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Pre Job'

  job:
    needs: [pre-job]
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Job'
